services:
  media-studio:
    container_name: media-studio
    build:
      context: .
    environment:
      MEDIA_DB_URL: sqlite:////app/data/media_studio.db
    ports:
      - "8088:8088"
    volumes:
      - media_studio_sqlite_data:/app/data
    restart: unless-stopped

volumes:
  media_studio_sqlite_data:
